service: serverless-s3
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
  profile: rafae


functions:
  uploadFile:
    handler: src/functions/uploadFile/index.handler
    events:
      - http:
          path: uploadFile
          method: post
          cors: true
  s3LambdaTrigger:
    handler: src/functions/s3Trigger/index.handler
    events:
      - s3:
          bucket: upload-bucket2
          event: s3:ObjectCreated:*
          existing: true
          rules:
            - prefix: Videos/
